

import win32con

from typing import NamedTuple

# Keyboard Related
WM_ACTIVATE = win32con.WM_ACTIVATE
WM_APPCOMMAND = 0x0319
WM_CHAR = win32con.WM_CHAR
WM_DEADCHAR = win32con.WM_DEADCHAR
WM_HOTKEY = win32con.WM_HOTKEY
WM_KEYDOWN = win32con.WM_KEYDOWN
WM_KEYUP = win32con.WM_KEYUP
WM_KILLFOCUS = win32con.WM_KILLFOCUS
WM_SETFOCUS = win32con.WM_SETFOCUS
WM_SYSDEADCHAR = win32con.WM_SYSDEADCHAR
WM_SYSKEYDOWN = win32con.WM_SYSKEYDOWN
WM_SYSKEYUP = win32con.WM_SYSKEYUP
WM_UNICHAR = 0x0109
keyboard_messages = NamedTuple('keyboard_messages', [
    ['WM_ACTIVATE', WM_ACTIVATE],
    ['WM_APPCOMMAND', WM_APPCOMMAND],
    ['WM_CHAR', WM_CHAR],
    ['WM_DEADCHAR', WM_DEADCHAR],
    ['WM_HOTKEY', WM_HOTKEY],
    ['WM_KEYDOWN', WM_KEYDOWN],
    ['WM_KEYUP', WM_KEYUP],
    ['WM_KILLFOCUS', WM_KILLFOCUS],
    ['WM_SETFOCUS', WM_SETFOCUS],
    ['WM_SYSDEADCHAR', WM_SYSDEADCHAR],
    ['WM_SYSKEYDOWN', WM_SYSKEYDOWN],
    ['WM_SYSKEYUP', WM_SYSKEYUP],
    ['WM_UNICHAR', WM_UNICHAR],
])

# Mouse Related
LEFT = win32con.VK_LBUTTON
RIGHT = win32con.VK_RBUTTON
MIDDLE = win32con.VK_MBUTTON
X1 = win32con.VK_XBUTTON1
X2 = win32con.VK_XBUTTON2
buttons = NamedTuple('buttons', [('LEFT', LEFT), ('RIGHT', RIGHT), ('MIDDLE', MIDDLE), ('X1', X1), ('X2', X2)])

WM_CAPTURECHANGED = win32con.WM_CAPTURECHANGED
WM_LBUTTONDBLCLK = win32con.WM_LBUTTONDBLCLK
WM_LBUTTONDOWN = win32con.WM_LBUTTONDOWN
WM_LBUTTONUP = win32con.WM_LBUTTONUP
WM_MBUTTONDBLCLK = win32con.WM_MBUTTONDBLCLK
WM_MBUTTONDOWN = win32con.WM_MBUTTONDOWN
WM_MBUTTONUP = win32con.WM_MBUTTONUP
WM_MOUSEACTIVATE = win32con.WM_MOUSEACTIVATE
WM_MOUSEHOVER = win32con.WM_MOUSEHOVER
WM_MOUSEHWHEEL = 0x020E
WM_MOUSELEAVE = win32con.WM_MOUSELEAVE
WM_MOUSEMOVE = win32con.WM_MOUSEMOVE
WM_MOUSEWHEEL = win32con.WM_MOUSEWHEEL
WM_NCHITTEST = win32con.WM_NCHITTEST
WM_NCLBUTTONDBLCLK = win32con.WM_NCLBUTTONDBLCLK
WM_NCLBUTTONDOWN = win32con.WM_NCLBUTTONDOWN
WM_NCLBUTTONUP = win32con.WM_NCLBUTTONUP
WM_NCMBUTTONDBLCLK = win32con.WM_NCMBUTTONDBLCLK
WM_NCMBUTTONDOWN = win32con.WM_NCMBUTTONDOWN
WM_NCMBUTTONUP = win32con.WM_NCMBUTTONUP
WM_NCMOUSEHOVER = 0x02A0
WM_NCMOUSELEAVE = 0x02A2
WM_NCMOUSEMOVE = win32con.WM_NCMOUSEMOVE
WM_NCRBUTTONDBLCLK = win32con.WM_NCRBUTTONDBLCLK
WM_NCRBUTTONDOWN = win32con.WM_NCRBUTTONDOWN
WM_NCRBUTTONUP = win32con.WM_NCRBUTTONUP
WM_NCXBUTTONDBLCLK = 0x00AD
WM_NCXBUTTONDOWN = 0x00AB
WM_NCXBUTTONUP = 0x00AC
WM_RBUTTONDBLCLK = win32con.WM_RBUTTONDBLCLK
WM_RBUTTONDOWN = win32con.WM_RBUTTONDOWN
WM_RBUTTONUP = win32con.WM_RBUTTONUP
WM_XBUTTONDBLCLK = 0x020D
WM_XBUTTONDOWN = 0x020B
WM_XBUTTONUP = 0x020C
mouse_messages = NamedTuple('mouse_messages', [
    ['WM_CAPTURECHANGED', WM_CAPTURECHANGED],
    ['WM_LBUTTONDBLCLK', WM_LBUTTONDBLCLK],
    ['WM_LBUTTONDOWN', WM_LBUTTONDOWN],
    ['WM_LBUTTONUP', WM_LBUTTONUP],
    ['WM_MBUTTONDBLCLK', WM_MBUTTONDBLCLK],
    ['WM_MBUTTONDOWN', WM_MBUTTONDOWN],
    ['WM_MBUTTONUP', WM_MBUTTONUP],
    ['WM_MOUSEACTIVATE', WM_MOUSEACTIVATE],
    ['WM_MOUSEHOVER', WM_MOUSEHOVER],
    ['WM_MOUSEHWHEEL', WM_MOUSEHWHEEL],
    ['WM_MOUSELEAVE', WM_MOUSELEAVE],
    ['WM_MOUSEMOVE', WM_MOUSEMOVE],
    ['WM_MOUSEWHEEL', WM_MOUSEWHEEL],
    ['WM_NCHITTEST', WM_NCHITTEST],
    ['WM_NCLBUTTONDBLCLK', WM_NCLBUTTONDBLCLK],
    ['WM_NCLBUTTONDOWN', WM_NCLBUTTONDOWN],
    ['WM_NCLBUTTONUP', WM_NCLBUTTONUP],
    ['WM_NCMBUTTONDBLCLK', WM_NCMBUTTONDBLCLK],
    ['WM_NCMBUTTONDOWN', WM_NCMBUTTONDOWN],
    ['WM_NCMBUTTONUP', WM_NCMBUTTONUP],
    ['WM_NCMOUSEHOVER', WM_NCMOUSEHOVER],
    ['WM_NCMOUSELEAVE', WM_NCMOUSELEAVE],
    ['WM_NCMOUSEMOVE', WM_NCMOUSEMOVE],
    ['WM_NCRBUTTONDBLCLK', WM_NCRBUTTONDBLCLK],
    ['WM_NCRBUTTONDOWN', WM_NCRBUTTONDOWN],
    ['WM_NCRBUTTONUP', WM_NCRBUTTONUP],
    ['WM_NCXBUTTONDBLCLK', WM_NCXBUTTONDBLCLK],
    ['WM_NCXBUTTONDOWN', WM_NCXBUTTONDOWN],
    ['WM_NCXBUTTONUP', WM_NCXBUTTONUP],
    ['WM_RBUTTONDBLCLK', WM_RBUTTONDBLCLK],
    ['WM_RBUTTONDOWN', WM_RBUTTONDOWN],
    ['WM_RBUTTONUP', WM_RBUTTONUP],
    ['WM_XBUTTONDBLCLK', WM_XBUTTONDBLCLK],
    ['WM_XBUTTONDOWN', WM_XBUTTONDOWN],
    ['WM_XBUTTONUP', WM_XBUTTONUP],
])


